name: "Request a New Repository"
description: "Fill out this form to request a new GitHub repository"
title: "[New Repo] <repo-name>"
labels: ["new-repo"]

body:
  - type: input
    id: repo_name
    attributes:
      label: "Repository Name:"
      description: "Enter the name of the new repository"
      placeholder: "my-new-repo"
    validations:
      required: true

  - type: textarea
    id: repo_description
    attributes:
      label: "Repository Description:"
      description: "Provide a brief description of the repository"
      placeholder: "This repository is used for..."
    validations:
      required: true

  - type: dropdown
    id: repo_visibility
    attributes:
      label: "Repository Visibility:"
      description: "Choose the visibility of the repository"
      options:
        - "public"
        - "private"
    validations:
      required: true
