name: "Create Repo PR"
on:
  issues:
    types: [opened, unlabeled, labeled]

jobs:
  create_pr:
    if: contains(github.event.issue.labels.*.name, 'new-repo')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Issue Data
        id: extract
        shell: bash
        run: |
          echo "REPO_NAME=$(jq -r '. | capture("Repository Name:\\s*(?<name>[^\n]+)") | .name' <<< "${{ github.event.issue.body }}")" >> $GITHUB_ENV
          echo "REPO_DESCRIPTION=$(jq -r '. | capture("Repository Description:\\s*(?<desc>[^\n]+)") | .desc' <<< "${{ github.event.issue.body }}")" >> $GITHUB_ENV
          echo "REPO_VISIBILITY=$(jq -r '. | capture("Repository Visibility:\\s*(?<vis>[^\n]+)") | .vis' <<< "${{ github.event.issue.body }}")" >> $GITHUB_ENV

      - name: Print Extracted Data
        run: |
          echo "Repository Name: ${{ env.REPO_NAME }}"
          echo "Repository Description: ${{ env.REPO_DESCRIPTION }}"
          echo "Repository Visibility: ${{ env.REPO_VISIBILITY }}"
