name: "Create Repo PR"
on:
  issues:
    types: [opened, unlabeled, labeled]

jobs:
  create_pr:
    if: contains(github.event.issue.labels.*.name, 'new-repo')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract issue body
        run: |
          echo "${{ github.event.issue.body }}" > issue_body.txt

      - name: Parse Repository Name
        run: |
          REPO_NAME=$(awk -F '|' '/\*\*Repository Name\*\*/ {gsub(/^[ \t]+|[ \t]+$/, "", $3); print $3}' issue_body.txt)
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Parse Description
        run: |
          DESCRIPTION=$(awk -F '|' '/\*\*Description\*\*/ {gsub(/^[ \t]+|[ \t]+$/, "", $3); print $3}' issue_body.txt)
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV

      - name: Parse Visibility
        run: |
          VISIBILITY=$(awk -F '|' '/\*\*Visibility\*\*/ {gsub(/^[ \t]+|[ \t]+$/, "", $3); print $3}' issue_body.txt)
          echo "VISIBILITY=$VISIBILITY" >> $GITHUB_ENV

      - name: Print Extracted Values
        run: |
          echo "Repository Name: $REPO_NAME"
          echo "Description: $DESCRIPTION"
          echo "Visibility: $VISIBILITY"
