name: "Create Repo PR"
on:
  issues:
    types: [opened, unlabeled, labeled]

jobs:
  create_pr:
    if: contains(github.event.issue.labels.*.name, 'new-repo')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Issue Data
        id: extract
        run: |
          echo "REPO_NAME=$(jq -r '.issue.body | capture("Repository Name: (?<name>.*)") | .name' <<< '${{ github.event.issue.body }}')" >> $GITHUB_ENV
          echo "REPO_DESCRIPTION=$(jq -r '.issue.body | capture("Repository Description: (?<desc>.*)") | .desc' <<< '${{ github.event.issue.body }}')" >> $GITHUB_ENV
          echo "REPO_VISIBILITY=$(jq -r '.issue.body | capture("Repository Visibility: (?<vis>.*)") | .vis' <<< '${{ github.event.issue.body }}')" >> $GITHUB_ENV
