name: "Terraform Apply"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Applu"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          TF_VAR_github_token: ${{ secrets.GH_TOKEN }}

      - name: "Terraform Apply"
        run: terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
